/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tlwl.demo.ice.main;

import com.tlwl.demo.base.BaseDBManager;

public class Server {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        int status = 0;
        // InputStream inStream = Server.class.getClassLoader().getResourceAsStream("db.properties");  
        
        // System.out.println(inStream);
        // System.exit(status); 
        BaseDBManager.getDBManager().initDBPool();
        System.out.println("-->init druid pool success");

        

        //
        // Try with resources block - communicator is automatically destroyed
        // at the end of this try block
        //
        try (com.zeroc.Ice.Communicator communicator = com.zeroc.Ice.Util.initialize(args,"config.server")) {
            communicator.getProperties().setProperty("Ice.Default.Package", "com.tlwl.demo");

            //
            // Install shutdown hook to (also) destroy communicator during JVM shutdown.
            // This ensures the communicator gets destroyed when the user interrupts the
            // application with Ctrl-C.
            //
            String port = "18001";
            String adapterName = "TlwlAdapter";
            String objectName = "tlwladapter";
            
            for (int i = 0; i < args.length; i++) {
                if (args[i].equals("-p")) {
                    i++;
                    port = args[i];
                }
            }

            if (port.equals("18002")) {
                objectName = "tlwladapter1";
                adapterName = "TlwlAdapter1";
            } else if (port.equals("18003")) {
                objectName = "tlwladapter2";
                adapterName = "TlwlAdapter2";
            } else if (port.equals("18004")) {
                objectName = "tlwladapter3";
                adapterName = "TlwlAdapter3";
            } else if (port.equals("18005")) {
                objectName = "tlwladapter4";
                adapterName = "TlwlAdapter4";
            }

            com.zeroc.Ice.ObjectAdapter adapter = communicator.createObjectAdapter(adapterName);
            // com.zeroc.Ice.Object object = new RequestI();
            adapter.add(new RequestI(), com.zeroc.Ice.Util.stringToIdentity(objectName));

            adapter.activate();
            System.out.println("-->server start success with:"+port);
            communicator.waitForShutdown();
        }catch (Exception e) {
            System.out.println(e.toString());
        }

        System.exit(status);
    }
}