/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tlwl.demo.ice.main;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServerTest {
    @Test public void testServerHasAGreeting() {
        Server classUnderTest = new Server();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
